version: '3'

services:
  db:
    image: mysql:5.7
    container_name: todo-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: larauser
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - db_data:/var/lib/mysql
    ports:
    - 3360:3306

volumes:
  db_data: {}